package toolcatalog

func agentTaskManagerTemplates() []entryTemplate {
	return []entryTemplate{
		{Name: "readArtifact", Category: "Artifact", Summary: "Read an artifact body by artifact id."},
		{Name: "writeArtifact", Category: "Artifact", Summary: "Write a generic artifact with optional metadata."},
		{Name: "storeTaskArtifact", Category: "Artifact", Summary: "Store a task artifact without extra metadata."},
		{Name: "loadTaskArtifacts", Category: "Artifact", Summary: "Load artifacts for a task, optionally narrowed to a worker task."},
		{Name: "storeDiffArtifact", Category: "Artifact", Summary: "Store a diff artifact for a worker task."},
		{Name: "loadDiffArtifact", Category: "Artifact", Summary: "Load a diff artifact body by artifact id."},
		{Name: "cacheTaskContext", Category: "Cache", Summary: "Warm task context cache for a task."},
		{Name: "getCachedTaskContext", Category: "Cache", Summary: "Read cached task context for a task."},
		{Name: "cacheValidationSummary", Category: "Cache", Summary: "Run validation to warm the validation summary cache."},
		{Name: "getCachedValidationSummary", Category: "Cache", Summary: "Read cached validation summary data."},
		{Name: "invalidateTaskCache", Category: "Cache", Summary: "Invalidate cached task context for a task."},
		{Name: "warmDashboardCache", Category: "Cache", Summary: "Warm dashboard cache state."},
		{Name: "loadTaskContext", Category: "Context", Summary: "Load the aggregated task context payload."},
		{Name: "loadArchitectureRules", Category: "Context", Summary: "Read RULES.md."},
		{Name: "loadExamples", Category: "Context", Summary: "Read EXAMPLES.md."},
		{Name: "loadValidationHistory", Category: "Context", Summary: "Load stored validation history for a task."},
		{Name: "loadDashboardSummary", Category: "Context", Summary: "Load the current dashboard summary payload."},
		{Name: "loadChatState", Category: "Context", Summary: "Load a chat thread detail payload."},
		{Name: "searchSemanticContext", Category: "Context", Summary: "Search stored semantic context by project and query text."},
		{Name: "loadSiblingTaskSummaries", Category: "Context", Summary: "Load sibling worker summaries for a task."},
		{Name: "storeSharedTaskContext", Category: "Context", Summary: "Store a shared task context entry."},
		{Name: "loadSharedTaskContext", Category: "Context", Summary: "Load shared task context entries for a task."},
		{Name: "createTaskBatch", Category: "Orchestration", Summary: "Create an overseer task batch and queue worker tasks."},
		{Name: "claimWorkerTask", Category: "Orchestration", Summary: "Claim the next queued worker task in a batch."},
		{Name: "assignWorkerTask", Category: "Orchestration", Summary: "Assign a worker task to an agent session and transport."},
		{Name: "reassignWorkerTask", Category: "Orchestration", Summary: "Reassign a worker task after timeout or failure."},
		{Name: "completeWorkerTask", Category: "Orchestration", Summary: "Mark a worker task completed."},
		{Name: "failWorkerTask", Category: "Orchestration", Summary: "Mark a worker task failed."},
		{Name: "deadLetterWorkerTask", Category: "Orchestration", Summary: "Route a worker task into dead-letter state."},
		{Name: "createCleanupReviewTask", Category: "Orchestration", Summary: "Create a cleanup review task for a diff artifact."},
		{Name: "submitWorkerCheckIn", Category: "Orchestration", Summary: "Store a worker progress check-in."},
		{Name: "heartbeatWorker", Category: "Orchestration", Summary: "Refresh a worker heartbeat."},
		{Name: "markWorkerDead", Category: "Orchestration", Summary: "Mark a worker dead after heartbeat timeout."},
		{Name: "registerWorker", Category: "Orchestration", Summary: "Register a worker session."},
		{Name: "updateWorkerLease", Category: "Orchestration", Summary: "Refresh worker lease and heartbeat."},
		{Name: "registerCleanupAgent", Category: "Orchestration", Summary: "Register the cleanup agent session."},
		{Name: "submitCleanupReview", Category: "Orchestration", Summary: "Store a cleanup review result."},
		{Name: "markCleanupReviewRequired", Category: "Orchestration", Summary: "Mark cleanup review as required."},
		{Name: "markCleanupApproved", Category: "Orchestration", Summary: "Mark cleanup review approved."},
		{Name: "markCleanupRejected", Category: "Orchestration", Summary: "Mark cleanup review rejected with findings."},
		{Name: "mergeWorkerOutputs", Category: "Orchestration", Summary: "Merge worker output summaries for a batch."},
		{Name: "approvePatch", Category: "Orchestration", Summary: "Approve a patch decision after validation and cleanup review."},
		{Name: "rejectPatch", Category: "Orchestration", Summary: "Reject a patch decision and require rework."},
		{Name: "storeOverseerDecision", Category: "Orchestration", Summary: "Store an overseer decision record."},
		{Name: "storeRunSummary", Category: "Orchestration", Summary: "Store the final run summary for a batch."},
		{Name: "runAutonomousCycle", Category: "Orchestration", Summary: "Run one autonomous orchestration cycle."},
		{Name: "publishDashboardUpdate", Category: "Orchestration", Summary: "Warm and republish dashboard summary state."},
		{Name: "planGitCommit", Category: "Repo Workflow", Summary: "Render the deterministic branch name and verbose commit plan without mutating git state."},
		{Name: "prepareGitBranch", Category: "Repo Workflow", Summary: "Create or switch to the deterministic concern branch."},
		{Name: "createGitCommit", Category: "Repo Workflow", Summary: "Stage and commit the current concern through the first-party git workflow."},
		{Name: "stageSharedRepoSnapshot", Category: "Repo Workflow", Summary: "Decode an uploaded repository archive and stage it into a local temporary workspace."},
		{Name: "runArchUnitValidation", Category: "Validation", Summary: "Run ArchUnit validation rules."},
		{Name: "runSpoonValidation", Category: "Validation", Summary: "Run Spoon source-shape validation."},
		{Name: "runIntegrationTests", Category: "Validation", Summary: "Run repository integration tests."},
		{Name: "validatePatchScope", Category: "Validation", Summary: "Check whether a diff stays within allowed patch scope."},
		{Name: "storeValidationReport", Category: "Validation", Summary: "Run validation and store the report."},
		{Name: "runCleanupDiffReview", Category: "Validation", Summary: "Run cleanup diff review for a cleanup review id."},
		{Name: "storeSemanticDocument", Category: "Vector Memory", Summary: "Chunk, embed, and store semantic payloads for a task."},
		{Name: "searchSemanticChunks", Category: "Vector Memory", Summary: "Search semantic chunks and return stored payload text or code."},
		{Name: "searchSemanticHistory", Category: "Vector Memory", Summary: "Search semantic task history chunks."},
		{Name: "searchKnowledgeIndex", Category: "Vector Memory", Summary: "Search indexed knowledge content."},
		{Name: "reindexSemanticKnowledge", Category: "Vector Memory", Summary: "Rebuild the configured semantic knowledge index."},
		{Name: "reindexConfiguredCodebases", Category: "Vector Memory", Summary: "Rebuild semantic indexes for configured codebases."},
		{Name: "attachSemanticDocumentToTask", Category: "Vector Memory", Summary: "Attach a semantic document to a task and index it."},
		{Name: "purgeLegacySemanticCollection", Category: "Vector Memory", Summary: "Delete the legacy shared Qdrant collection."},
		{Name: "storeTaskEmbedding", Category: "Vector Memory", Summary: "Store chunked task embedding payloads into vector memory."},
		{Name: "recordMemory", Category: "Vector Memory", Summary: "Persist one intentional distilled durable memory."},
		{Name: "searchRelatedContexts", Category: "Vector Memory", Summary: "Search related semantic context chunks."},
		{Name: "searchPriorFixes", Category: "Vector Memory", Summary: "Search semantic task history for prior fixes and reviews."},
		{Name: "attachSemanticContextToTask", Category: "Vector Memory", Summary: "Store shared task context and index it through the semantic pipeline."},
		{Name: "intakeHarnessTask", Category: "Harness", Summary: "Accept parent work and persist shared harness state."},
		{Name: "routeHarnessTask", Category: "Harness", Summary: "Route parent work into typed worker plans without creating tasks."},
		{Name: "loadHarnessState", Category: "Harness", Summary: "Load shared task, agent, persistence, and dashboard state for a harness task."},
		{Name: "runHarnessToolBundle", Category: "Harness", Summary: "Run the harness bundle broker for repo, worker, or Java context."},
		{Name: "runHarnessApprovalGate", Category: "Harness", Summary: "Run cleanup, validation, integration-test, and patch-scope gates for a worker task."},
		{Name: "loadCleanJavaTaskContext", Category: "Harness", Summary: "Build deterministic clean Java task context for harness use."},
		{Name: "runCleanJavaHarness", Category: "Harness", Summary: "Run the full deterministic clean Java harness."},
		{Name: "runJavaIntegrationHarness", Category: "Harness", Summary: "Run the deterministic Java integration-test harness."},
		{Name: "registerComputerUseRunner", Category: "Computer Use", Summary: "Register an external computer-use runner."},
		{Name: "listComputerUseRunners", Category: "Computer Use", Summary: "List registered computer-use runners."},
		{Name: "startComputerUseSession", Category: "Computer Use", Summary: "Start a computer-use session."},
		{Name: "launchComputerUseProcess", Category: "Computer Use", Summary: "Launch the configured external process for a computer-use session."},
		{Name: "captureComputerUseWindow", Category: "Computer Use", Summary: "Capture the active computer-use window frame."},
		{Name: "sendComputerUseInput", Category: "Computer Use", Summary: "Send cooperative computer-use input."},
		{Name: "waitForComputerUseVisionMatch", Category: "Computer Use", Summary: "Wait for a vision match inside the remote client surface."},
		{Name: "stopComputerUseSession", Category: "Computer Use", Summary: "Stop a computer-use session."},
	}
}
